spring:
  profiles:
    active: console
application:
  version: 0.0.1
app-config:
  base-csv-resource-name: "/simple-exam-5-questions.csv"
  right-answers-to-success: 4
shell:
  interactive:
    enabled: false

---
spring:
  profiles: shell

  shell:
    interactive:
      enabled: true